name: Piscine Scraper

on:
  schedule:
    - cron: '*/5 * * * *'  # Tourne toutes les 5 minutes
  workflow_dispatch:        # Permet aussi de le lancer manuellement (bouton)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:            # Donne la permission d'écrire dans le repo
      contents: write

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des librairies
        run: |
          pip install requests pandas

      - name: Lancement du script
        run: python main.py

      - name: Sauvegarde des données (Commit)
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add historique_piscine.csv
          git commit -m "Mise à jour données piscine" || echo "Rien à modifier"
          git push
